<?xml version="1.0" encoding="utf-8"?><Database Name="StudentInformation" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=2NA\SQLEXPRESS;Initial Catalog=StudentInformation;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="StudentInformationConnectionString" Provider="System.Data.SqlClient" />
</Database>